robot_bridge:
  ros__parameters:
    mcu_a:
      ip: 192.168.1.120    # set to UNO A IP
      port: 5555
    mcu_b:
      ip: 192.168.1.121    # set to UNO B IP
      port: 5556
    watchdog_ms: 200
